import test from "node:test";
import assert from "node:assert/strict";
import {assessMarket} from "../lib/context.ts";
import {assetsIn,headlineContext} from "../lib/subjects.ts";
import {parseSearchTrends,parseSentiment,fetchOnline} from "../lib/online.ts";
import {fetchNews} from "../lib/news.ts";
import {initialState,advancePaper} from "../lib/paper.ts";
const now=Date.parse("2026-09-25T21:00:00Z");
const health=(name)=>({name,url:"https://example.org",ok:true,checkedAt:now,message:"fixture"});
function state(){const s=initialState(now);s.newsHealth={ok:true,checkedAt:now,sources:5,message:"fixture"};s.online={checkedAt:now,searchSources:[health("Google Trends US"),health("Google Trends IN")],searches:[],sentiment:{value:50,label:"Neutral",publishedAt:now-3600000,checkedAt:now},sentimentHealth:health("Alternative.me")};return s;}
function market(action="LONG"){return {pair:"B-BTC_USDT",symbol:"BTC",price:100,bid:99.99,ask:100.01,spreadBps:2,turnover:1e6,change:1,funding:0,updatedAt:now,history:[],instrument:{step:.001,tick:.01,minimum:.001,minNotional:5,maxQuantity:1000,feeRate:.00075,contractValue:1,active:true},signal:{action,entry:100,stop:98,target:103.6,strategy:"fixture",regime:"Uptrend",reason:action==="WAIT"?"No complete setup; waiting for price and volume confirmation":"Fixture price setup",barTime:now-60000}};}
function story(title,source="CoinDesk",extra={}){return {id:source+title,title,url:"https://example.org/"+encodeURIComponent(title),source,publishedAt:now-60000,seenAt:now-30000,assets:assetsIn(title),verified:false,...headlineContext(title),...extra};}
function positive(){return [story("Bitcoin ETFs record inflows"),story("New Bitcoin fund sees inflows","Decrypt")];}

test("aliases distinguish Bitcoin Cash and ambiguous everyday words",()=>{assert.deepEqual(assetsIn("Bitcoin Cash gains"),["BCH"]);assert.deepEqual(assetsIn("Traders near the link"),[]);assert.ok(assetsIn("Zcash adoption").includes("ZEC"));});
test("negation, rumours and predictions have no directional vote",()=>{for(const title of ["Bitcoin ETF not approved","Bitcoin may attract inflows","Rumor: Solana ETF approved","Bitcoin ETF approval?"])assert.equal(headlineContext(title).tone,"NEUTRAL");});
test("fresh negative news changes an otherwise valid long to WAIT",()=>{const s=state();s.news=[story("Bitcoin ETF outflows accelerate"),story("Bitcoin funds record outflows","Decrypt")];const v=assessMarket(market(),s,now);assert.equal(v.signal.action,"WAIT");assert.match(v.signal.reason,/conflicts/);assert.equal(v.assessment.newsBias,"NEGATIVE");});
test("one publisher or a duplicated headline does not create corroboration",()=>{const s=state();s.news=[story("Bitcoin ETF outflows accelerate"),story("Bitcoin ETF outflows accelerate","Decrypt")];assert.equal(assessMarket(market(),s,now).assessment.newsBias,"NEUTRAL");});
test("future, stale and not-yet-seen stories cannot affect a decision",()=>{for(const extra of [{publishedAt:now+1},{publishedAt:now-3*3600000},{seenAt:now+1}]){const s=state();s.news=[story("Bitcoin ETF outflows", "CoinDesk",extra),story("Bitcoin funds record outflows","Decrypt",extra)];assert.equal(assessMarket(market(),s,now).assessment.newsBias,"NEUTRAL");}});
test("single-publisher security reports pause affected entries; unrelated coins remain eligible",()=>{const s=state();s.news=[story("Bitcoin network outage reported")];assert.equal(assessMarket(market(),s,now).signal.action,"WAIT");s.news=[story("Solana network outage reported")];assert.equal(assessMarket(market(),s,now).signal.action,"LONG");});
test("missing news or search coverage fails closed but daily sentiment is optional",()=>{const s=state();delete s.online;assert.equal(assessMarket(market(),s,now).signal.action,"WAIT");const ready=state();ready.newsHealth.ok=false;assert.equal(assessMarket(market(),ready,now).signal.action,"WAIT");const partial=state();partial.online.sentimentHealth.ok=false;const r=assessMarket(market(),partial,now);assert.equal(r.signal.action,"LONG");assert.equal(r.assessment.coverage,"PARTIAL");assert.equal(r.assessment.sentiment,null);});
test("search attention alone cannot create an entry",()=>{const s=state();s.online.searches=[{query:"bitcoin",region:"US",url:"https://trends.google.com/trending?geo=US",publishedAt:now-60000,assets:["BTC"],traffic:"10000+"}];assert.equal(assessMarket(market("WAIT"),s,now).signal.action,"WAIT");});
test("news and search attention can create a price-confirmed paper candidate, never override invalid candles",()=>{const s=state();s.news=positive();s.online.searches=[{query:"bitcoin etf",region:"US",url:"https://trends.google.com/trending?geo=US",publishedAt:now-60000,assets:["BTC"],traffic:"10000+"}];const m=market("WAIT");m.history=Array.from({length:220},(_,i)=>({time:now-(220-i)*60000,open:100+i*.01,close:100+i*.01+.025,high:100+i*.01+.05,low:99.98+i*.01,volume:i===219?30:10}));m.history.at(-1).close+=.2;m.history.at(-1).high+=.2;const r=assessMarket(m,s,now);assert.equal(r.signal.action,"LONG");assert.equal(r.signal.strategy,"News and attention confirmation");assert.ok(r.signal.stop<r.signal.entry&&r.signal.target>r.signal.entry);m.signal.reason="Candle gap detected; entries paused";assert.equal(assessMarket(m,s,now).signal.action,"WAIT");});
test("paper ledger saves entry evidence and prevents same-bar duplicate entries",()=>{const s=state();s.news=positive();s.markets=[market()];advancePaper(s,now);assert.equal(s.portfolio.trades.length,1);assert.equal(s.portfolio.trades[0].entryEvidence.newsBias,"POSITIVE");s.news=[];advancePaper(s,now+1000);assert.equal(s.portfolio.trades.length,1);assert.equal(s.portfolio.trades[0].entryEvidence.newsBias,"POSITIVE");});
test("a missing online source cannot prevent supervision of an open stop loss",()=>{const s=state();s.markets=[market()];advancePaper(s,now);delete s.online;s.markets[0].bid=95;s.markets[0].ask=95.01;s.markets[0].price=95;advancePaper(s,now+1000);assert.equal(s.portfolio.trades[0].status,"CLOSED");assert.equal(s.portfolio.trades[0].exitReason,"Stop loss");});
test("regional search parsing filters irrelevant queries and future timestamps",()=>{const xml='<rss><item><title>Bitcoin price</title><ht:approx_traffic>5000+</ht:approx_traffic><pubDate>'+new Date(now-60000).toUTCString()+'</pubDate></item><item><title>cricket</title><pubDate>'+new Date(now-60000).toUTCString()+'</pubDate></item></rss>';const r=parseSearchTrends(xml,"IN",now);assert.equal(r.length,1);assert.equal(r[0].traffic,"5000+");assert.ok(r[0].assets.includes("BTC"));assert.throws(()=>parseSearchTrends('<html>blocked</html>',"IN",now));});
test("stale or future sentiment is rejected",()=>{for(const timestamp of [(now-49*3600000)/1000,(now+60000)/1000])assert.throws(()=>parseSentiment({data:[{value:"50",timestamp}]},now));assert.equal(parseSentiment({data:[{value:"71",timestamp:now/1000,value_classification:"Greed"}]},now).value,71);});
test("source failure preserves last data as unavailable instead of inventing neutral readings",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response("unavailable",{status:503});try{const prior=state().online;const r=await fetchOnline(prior);assert.equal(r.sentiment.value,50);assert.equal(r.sentimentHealth.ok,false);assert.ok(r.searchSources.every(s=>!s.ok));const n=await fetchNews([story("Bitcoin ETF inflows")]);assert.equal(n.health.ok,false);assert.equal(n.health.sources,0);}finally{globalThis.fetch=original;}});
