import type {Candle,Backtest,Settings,Trade,Instrument} from "./types";
import {signal,sizeTrade,exitPrice} from "./strategy.ts";
export function runBacktest(pair:string,c:Candle[],s:Settings,inst:Instrument):Backtest{if(c.length<500)throw Error("At least 500 valid one-minute bars are needed");const split=Math.floor(c.length*.7);let balance=s.paperCapital,peak=balance,maxDD=0,lastIndex=split;const results:number[]=[];let position:Trade|null=null;const fees=Math.max(s.feeBps/10000,inst.feeRate);for(let i=split;i<c.length;i++){const bar=c[i];lastIndex=i;if(position){const ex=exitPrice(position,bar,s.slippageBps);if(ex){const gross=(ex.price-position.entry)*position.quantity*(position.side==="LONG"?1:-1);const funding=position.quantity*position.entry*.0001*Math.ceil((bar.time-position.openedAt)/(8*3600000));const pnl=gross-position.fees-ex.price*position.quantity*fees-funding;balance+=gross-ex.price*position.quantity*fees-funding;results.push(pnl);position=null;}}
 if(!position){const sig=signal(c.slice(Math.max(0,i-360),i),bar.time);if(sig.action!=="WAIT"&&sig.stop&&sig.entry){const dir=sig.action==="LONG"?1:-1,entry=bar.open*(1+dir*(s.slippageBps+2)/10000),distance=Math.abs(sig.entry-sig.stop);const size=sizeTrade(balance,entry,entry-dir*distance,inst,s,balance);if(size.quantity>0){const entryFee=entry*size.quantity*fees;balance-=entryFee;position={id:"backtest-"+i,pair,side:sig.action,quantity:size.quantity,entry,stop:entry-dir*distance,target:entry+dir*distance*1.8,openedAt:bar.time,pnl:0,fees:entryFee,funding:0,plannedRisk:size.risk,status:"OPEN",lastBarTime:bar.time,lastFundingAt:bar.time,strategy:sig.strategy};
 // The entry is at this bar's open, so its complete range is part of execution testing.
 const ex=exitPrice(position,bar,s.slippageBps);if(ex){const gross=(ex.price-entry)*size.quantity*dir,pnl=gross-entryFee-ex.price*size.quantity*fees;balance+=gross-ex.price*size.quantity*fees;results.push(pnl);position=null;}
 }}}const e=balance+(position?(bar.close-position.entry)*position.quantity*(position.side==="LONG"?1:-1):0);peak=Math.max(peak,e);maxDD=Math.max(maxDD,(peak-e)/peak*100);if(e<=s.paperCapital*(1-s.drawdownLimitPct/100))break;}
 if(position){const last=c[lastIndex];const dir=position.side==="LONG"?1:-1,price=last.close*(1-dir*s.slippageBps/10000),gross=(price-position.entry)*position.quantity*dir,funding=position.quantity*position.entry*.0001*Math.ceil((last.time-position.openedAt)/(8*3600000));balance+=gross-price*position.quantity*fees-funding;results.push(gross-position.fees-price*position.quantity*fees-funding);}
 peak=Math.max(peak,balance);maxDD=Math.max(maxDD,(peak-balance)/peak*100);
 const gains=results.filter(x=>x>0).reduce((a,b)=>a+b,0),losses=-results.filter(x=>x<0).reduce((a,b)=>a+b,0);return {pair,bars:c.length,days:(c.at(-1)!.time-c[0].time)/86400000,trainBars:split,testBars:lastIndex-split+1,trades:results.length,netPnl:balance-s.paperCapital,winRate:results.length?results.filter(x=>x>0).length/results.length*100:null,profitFactor:losses>0?gains/losses:null,maxDrawdownPct:maxDD,expectancy:results.length?(balance-s.paperCapital)/results.length:null,startedAt:c[split].time,finishedAt:Date.now(),mode:"Recent-data diagnostic; not independent validation",limitations:["Fixed baseline rules; no trained prediction model.","Today's universe creates selection bias.","Conservative fee/slippage assumptions; funding is a cost reserve.","No historical depth, partial fills, or event-time news simulation.","This short diagnostic cannot unlock live trading."]};}
