import type {Candle,Market,Instrument} from "./types";
import {signal} from "./strategy.ts";
const API="https://api.coindcx.com",PUBLIC="https://public.coindcx.com";
export async function fetchJson(url:string,init:RequestInit={}):Promise<any>{const r=await fetch(url,{...init,signal:AbortSignal.timeout(10000),headers:{"Accept":"application/json",...init.headers}});if(!r.ok)throw Error("Exchange request failed ("+r.status+")");const v=await r.json();return v;}
export function normalizeCandles(raw:unknown):Candle[]{const obj=raw as {data?:unknown[]};const data=Array.isArray(raw)?raw:obj?.data;if(!Array.isArray(data))throw Error("Unexpected candle response");const rows=data.map((v:any)=>({time:Number(v.time)<1e12?Number(v.time)*1000:Number(v.time),open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close),volume:Number(v.volume)})).filter(x=>Object.values(x).every(Number.isFinite)&&x.open>0&&x.close>0&&x.low>0&&x.high>=Math.max(x.open,x.close,x.low)&&x.low<=Math.min(x.open,x.close)&&x.volume>=0);return [...new Map(rows.map(x=>[x.time,x])).values()].sort((a,b)=>a.time-b.time);}
export async function candles(pair:string,count=360,to=Date.now()){if(!/^B-[A-Z0-9]+_USDT$/.test(pair))throw Error("Invalid instrument");const qs=new URLSearchParams({pair,from:String(Math.floor(to/1000)-count*60),to:String(Math.floor(to/1000)),resolution:"1",pcode:"f"});return normalizeCandles(await fetchJson(PUBLIC+"/market_data/candlesticks?"+qs));}
export async function instrument(pair:string):Promise<Instrument>{const r=await fetchJson(API+"/exchange/v1/derivatives/futures/data/instrument?pair="+encodeURIComponent(pair)+"&margin_currency_short_name=USDT");const i=r.instrument;if(!i||i.is_inverse||i.is_quanto||Number(i.unit_contract_value)!==1)throw Error("Unsupported contract structure");return {step:Number(i.quantity_increment),tick:Number(i.price_increment),minimum:Math.max(Number(i.min_quantity),Number(i.min_trade_size)),minNotional:Number(i.min_notional),maxQuantity:Math.min(Number(i.max_quantity),Number(i.max_market_order_quantity)),feeRate:Number(i.taker_fee)/100,contractValue:1,active:i.status==="active"&&!i.exit_only};}
const blocked=/^(USDT|USDC|DAI|TUSD|FDUSD|USDE|USD1|PAXG|WBTC|WETH|STETH|BTCDOM|DEFI|1000.*)$/;
export async function marketSnapshot(previous:Market[]=[],held:string[]=[],rotate=true):Promise<Market[]>{
 const [prices,active]=await Promise.all([fetchJson(PUBLIC+"/market_data/v3/current_prices/futures/rt"),fetchJson(API+"/exchange/v1/derivatives/futures/data/active_instruments?margin_currency_short_name[]=USDT")]);
 if(!prices?.prices||!Array.isArray(active))throw Error("Unexpected futures universe response");
 const now=Date.now();const candidates=Object.entries(prices.prices).filter(([pair,v]:[string,any])=>active.includes(pair)&&/^B-[A-Z0-9]+_USDT$/.test(pair)&&!blocked.test(pair.slice(2,-5))&&Number(v.ls)>0&&Number(v.v)>0).sort((a:any,b:any)=>Number(b[1].v)*Number(b[1].ls)-Number(a[1].v)*Number(a[1].ls));
 const fixed=[...new Set([...held,...(!rotate?previous.map(x=>x.pair):[])])].slice(0,5);const pool=[...new Set([...fixed,...candidates.slice(0,12).map(x=>x[0])])];const out:Market[]=[];
 // Bounded concurrency avoids overwhelming the public endpoints.
 for(let j=0;j<pool.length&&out.length<5;j+=3){const group=await Promise.allSettled(pool.slice(j,j+3).map(async pair=>{const p=prices.prices[pair];if(!p)throw Error("Instrument has no current quote");const old=previous.find(x=>x.pair===pair);const [book,hist,inst]=await Promise.all([fetchJson(PUBLIC+"/market_data/v3/orderbook/"+pair+"-futures/20"),old&&now-(old.history.at(-1)?.time||0)<60000?Promise.resolve(old.history):candles(pair,360),old?.instrument&&(!rotate||held.includes(pair))?Promise.resolve(old.instrument):instrument(pair)]);const bid=Math.max(...Object.keys(book.bids||{}).map(Number)),ask=Math.min(...Object.keys(book.asks||{}).map(Number)),price=Number(p.ls);const updatedAt=Math.min(Number(book.ts),Number(p.btST||prices.ts));if(!Number.isFinite(bid)||!Number.isFinite(ask)||bid<=0||ask<bid||!Number.isFinite(updatedAt))throw Error("Invalid order book");const spreadBps=(ask-bid)/((ask+bid)/2)*10000;const m:Market={pair,symbol:pair.slice(2,-5),price,bid,ask,spreadBps,turnover:Number(p.v)*price,change:Number(p.pc)||0,funding:Number(p.fr)||0,updatedAt,history:hist,signal:signal(hist,now),instrument:inst};if(!held.includes(pair)&&(!inst.active||hist.length<210||spreadBps>30||now-updatedAt>30000))throw Error("Instrument failed liquidity or freshness checks");return m;}));for(const g of group)if(g.status==="fulfilled")out.push(g.value);}
 const priority=new Set(rotate?held:fixed);const selected=[...out.filter(x=>priority.has(x.pair)),...out.filter(x=>!priority.has(x.pair)).sort((a,b)=>b.turnover/(1+b.spreadBps)-a.turnover/(1+a.spreadBps))].slice(0,5);
 if(!selected.length)throw Error("No eligible fresh futures quotes available");return selected;
}
export async function signedRead(path:string,key:string,secret:string,data:Record<string,unknown>={}){const allowed=["/exchange/v1/derivatives/futures/positions","/exchange/v1/derivatives/futures/orders"];if(!allowed.includes(path))throw Error("Read-only adapter rejected this operation");const body=JSON.stringify({timestamp:Date.now(),...data});const enc=new TextEncoder(),h=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("HMAC",h,enc.encode(body));const hex=Array.from(new Uint8Array(sig)).map(x=>x.toString(16).padStart(2,"0")).join("");return fetchJson(API+path,{method:"POST",headers:{"Content-Type":"application/json","X-AUTH-APIKEY":key,"X-AUTH-SIGNATURE":hex},body});}
