import type {NewsItem,SourceStatus} from "./types";
import {assetsIn,headlineContext} from "./subjects.ts";
export const FEEDS=[{name:"Federal Reserve",url:"https://www.federalreserve.gov/feeds/press_all.xml",official:true},{name:"SEC",url:"https://www.sec.gov/news/pressreleases.rss",official:true},{name:"CoinDesk",url:"https://www.coindesk.com/arc/outboundfeeds/rss/",official:false},{name:"Cointelegraph",url:"https://cointelegraph.com/rss",official:false},{name:"Decrypt",url:"https://decrypt.co/feed",official:false}];
export const clean=(x:string)=>x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]*>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").trim();
export function tag(x:string,name:string){return clean(x.match(new RegExp("<"+name+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+name+">","i"))?.[1]||"");}
export async function publicText(url:string,accept:string){const r=await fetch(url,{signal:AbortSignal.timeout(8000),headers:{Accept:accept,"User-Agent":"DCX-Pilot/1.0 (paper research)"}});if(!r.ok)throw Error("Source HTTP "+r.status);if(Number(r.headers.get("content-length")||0)>1500000)throw Error("Source too large");const reader=r.body?.getReader();if(!reader)throw Error("Empty response");const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>1500000){await reader.cancel();throw Error("Source too large");}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.length;}return new TextDecoder().decode(all);}
export function parseFeed(xml:string,source:string,official:boolean,now=Date.now()):NewsItem[]{const items=xml.match(/<item[\s>][\s\S]*?<\/item>/gi)||xml.match(/<entry[\s>][\s\S]*?<\/entry>/gi)||[];return items.slice(0,40).map(x=>{const title=tag(x,"title").slice(0,400),url=tag(x,"link")||x.match(/<link[^>]+href=["']([^"']+)["']/)?.[1]||"",publishedAt=Date.parse(tag(x,"pubDate")||tag(x,"published")||tag(x,"updated"));return {id:source+":"+url,title,url,source,publishedAt,seenAt:now,assets:assetsIn(title),verified:official,...headlineContext(title)};}).filter(x=>x.title&&/^https:\/\//.test(x.url)&&Number.isFinite(x.publishedAt)&&x.publishedAt<=now&&now-x.publishedAt<7*86400000);}
export async function fetchNews(previous:NewsItem[]=[]){const now=Date.now();const feeds:SourceStatus[]=[];const results=await Promise.allSettled(FEEDS.map(async f=>{try{const xml=await publicText(f.url,"application/rss+xml,application/xml,text/xml");if(!/<rss|<feed/i.test(xml))throw Error("Invalid feed");feeds.push({name:f.name,url:f.url,ok:true,checkedAt:now,message:"Feed checked"});return parseFeed(xml,f.name,f.official,now);}catch{feeds.push({name:f.name,url:f.url,ok:false,checkedAt:now,message:"Feed unavailable"});return [];}}));const seen=new Map(previous.map(x=>[x.id,x.seenAt]));const current=results.flatMap(r=>r.status==="fulfilled"?r.value:[]).map(x=>({...x,seenAt:seen.get(x.id)||now}));const freshNames=new Set(feeds.filter(f=>f.ok).map(f=>f.name));const retained=previous.filter(x=>!freshNames.has(x.source)&&now-x.publishedAt<86400000);const unique=[...new Map([...current,...retained].map(x=>[x.title.toLowerCase().replace(/[^a-z0-9]/g,""),x])).values()].sort((a,b)=>b.publishedAt-a.publishedAt).slice(0,160);const sources=feeds.filter(f=>f.ok).length,crypto=feeds.filter(f=>f.ok&&["CoinDesk","Cointelegraph","Decrypt"].includes(f.name)).length,official=feeds.some(f=>f.ok&&["Federal Reserve","SEC"].includes(f.name));const ok=crypto>=2&&official;return {items:unique,health:{ok,checkedAt:now,sources,total:FEEDS.length,feeds,message:ok?"Headlines matched to coins and checked for event direction, uncertainty and risk":"News coverage incomplete; new entries wait for recovery"}};}
export function newsBlocks(items:NewsItem[],now=Date.now()){return items.some(x=>x.verified&&x.severity==="HIGH"&&!x.uncertain&&now>=x.publishedAt&&now-x.publishedAt<30*60000&&now>=x.seenAt&&now-x.seenAt<30*60000);}
