import type {DeskState,Portfolio,Trade,Market,Settings} from "./types";
import {DEFAULT_SETTINGS,utcDayKeys,markPnl,sizeTrade,exitPrice} from "./strategy.ts";
import {newsBlocks} from "./news.ts";
export function event(p:Portfolio,type:string,message:string,pair?:string){p.events.unshift({id:crypto.randomUUID(),time:Date.now(),type,message,pair});p.events=p.events.slice(0,500);}
export function initialState(now=Date.now()):DeskState{const k=utcDayKeys(now),initial=DEFAULT_SETTINGS.paperCapital;return {settings:{...DEFAULT_SETTINGS},portfolio:{balance:initial,initial,peak:initial,dayStart:initial,weekStart:initial,dayKey:k.day,weekKey:k.week,startedAt:now,cooldownUntil:0,lossStreak:0,halted:null,trades:[],events:[{id:crypto.randomUUID(),time:now,type:"SYSTEM",message:"Paper observation enabled automatically. Live execution is locked."}],equityCurve:[{time:now,equity:initial}],lastScan:0,lastAttempt:0,lastSignalBars:{}},markets:[],news:[],newsHealth:{ok:false,checkedAt:0,sources:0,message:"News feeds have not been checked"},marketError:null,worker:{connected:false,lastHeartbeat:null,continuous:false,message:"Background worker not connected. Dashboard scans run while this page is open."},connection:{configured:false,verified:false,message:"CoinDCX account not connected"},backtest:null,version:0};}
export function equity(state:DeskState){return state.portfolio.balance+state.portfolio.trades.filter(t=>t.status==="OPEN").reduce((s,t)=>s+markPnl(t,state.markets.find(m=>m.pair===t.pair)?.price||t.entry),0);}
export function closePaper(state:DeskState,t:Trade,price:number,reason:string,at=Date.now()){if(t.status!=="OPEN")return;const feeRate=Math.max(state.settings.feeBps/10000,state.markets.find(x=>x.pair===t.pair)?.instrument?.feeRate||0);const fee=price*t.quantity*feeRate;const gross=markPnl(t,price);t.status="CLOSED";t.exit=price;t.closedAt=at;t.exitReason=reason;t.pnl=gross-t.fees-fee-t.funding;t.fees+=fee;state.portfolio.balance+=gross-fee;state.portfolio.lossStreak=t.pnl<0?state.portfolio.lossStreak+1:0;if(state.portfolio.lossStreak>=3)state.portfolio.cooldownUntil=at+3600000;event(state.portfolio,"EXIT",reason+" · "+t.pnl.toFixed(2)+" USDT net",t.pair);}
export function riskCheck(state:DeskState,now=Date.now()){const p=state.portfolio,s=state.settings,e=equity(state),k=utcDayKeys(now);if(k.day!==p.dayKey){p.dayKey=k.day;p.dayStart=e;}if(k.week!==p.weekKey){p.weekKey=k.week;p.weekStart=e;}p.peak=Math.max(p.peak,e);if(e<=p.dayStart*(1-s.dailyLimitPct/100))p.halted="Daily loss limit reached";if(e<=p.weekStart*(1-s.weeklyLimitPct/100))p.halted="Weekly loss limit reached";if(e<=p.peak*(1-s.drawdownLimitPct/100))p.halted="Maximum drawdown reached";if(p.halted)state.settings.running=false;return {equity:e,halted:p.halted};}
export function advancePaper(state:DeskState,now=Date.now()){const p=state.portfolio,s=state.settings;
 for(const t of p.trades.filter(t=>t.status==="OPEN")){const m=state.markets.find(x=>x.pair===t.pair);if(!m)continue;const newBars=m.history.filter(c=>c.time>=t.openedAt&&c.time>t.lastBarTime&&c.time+60000<=now);for(const bar of newBars){t.lastBarTime=bar.time;const exit=exitPrice(t,bar,s.slippageBps);if(exit){closePaper(state,t,exit.price,exit.reason,bar.time+60000);break;}}if(t.status!=="OPEN")continue;
 // Conservative holding-cost reserve. Actual historical funding isn't available in this paper model.
 const periods=Math.floor((now-t.lastFundingAt)/(8*3600000));if(periods>0){const cost=t.quantity*m.price*Math.max(Math.abs(m.funding),.0001)*periods;t.funding+=cost;p.balance-=cost;t.lastFundingAt+=periods*8*3600000;}
 if(now-m.updatedAt<=30000&&((t.side==="LONG"&&m.bid<=t.stop)||(t.side==="SHORT"&&m.ask>=t.stop)))closePaper(state,t,(t.side==="LONG"?m.bid:m.ask)*(1+(t.side==="LONG"?-1:1)*s.slippageBps/10000),"Stop loss");
 if(t.status==="OPEN"&&now-m.updatedAt<=30000&&((t.side==="LONG"&&m.bid>=t.target)||(t.side==="SHORT"&&m.ask<=t.target)))closePaper(state,t,t.target*(1+(t.side==="LONG"?-1:1)*s.slippageBps/10000),"Take profit");
 if(t.status==="OPEN"&&now-t.openedAt>=90*60000&&now-m.updatedAt<=30000)closePaper(state,t,(t.side==="LONG"?m.bid:m.ask)*(1+(t.side==="LONG"?-1:1)*s.slippageBps/10000),"Time exit");
 }
 const risk=riskCheck(state,now);if(risk.halted){for(const t of p.trades.filter(x=>x.status==="OPEN")){const m=state.markets.find(x=>x.pair===t.pair);if(m&&now-m.updatedAt<30000)closePaper(state,t,(t.side==="LONG"?m.bid:m.ask)*(1+(t.side==="LONG"?-1:1)*s.slippageBps/10000),risk.halted);}}
 const allOpenQuotesFresh=p.trades.filter(t=>t.status==="OPEN").every(t=>{const m=state.markets.find(m=>m.pair===t.pair);return m&&now-m.updatedAt<=15000;});
 if(s.running&&!p.halted&&allOpenQuotesFresh&&now>=p.cooldownUntil){for(const m of state.markets){const sig=m.signal,bar=sig.barTime||0;if(!bar||p.lastSignalBars[m.pair]===bar)continue;p.lastSignalBars[m.pair]=bar;const reject=(message:string)=>event(p,"SKIP",message,m.pair);if(sig.action==="WAIT"){reject(sig.reason);continue;}if(p.trades.filter(t=>t.status==="OPEN").length>=s.maxPositions){reject("Position limit reached");continue;}if(p.trades.some(t=>t.status==="OPEN"&&t.pair===m.pair)){reject("Position already open");continue;}if(now-m.updatedAt>15000||m.updatedAt>now+5000){reject("Quote is stale or clock is inconsistent");continue;}if(m.spreadBps>s.maxSpreadBps){reject("Spread exceeds limit");continue;}if(!m.instrument?.active){reject("Instrument is unavailable for entries");continue;}if(s.newsGuard&&(!state.newsHealth.ok||now-state.newsHealth.checkedAt>15*60000||newsBlocks(state.news,now))){reject("News risk guard paused this entry");continue;}
 const direction=sig.action==="LONG"?1:-1,entry=(direction===1?m.ask:m.bid)*(1+direction*s.slippageBps/10000),distance=Math.abs((sig.entry||entry)-(sig.stop||entry));if(!Number.isFinite(distance)||distance<=0){reject("No valid stop");continue;}
 const tick=m.instrument.tick;const stop=Number(((direction===1?Math.floor((entry-distance)/tick):Math.ceil((entry+distance)/tick))*tick).toPrecision(12)),target=Number(((direction===1?Math.floor((entry+distance*1.8)/tick):Math.ceil((entry-distance*1.8)/tick))*tick).toPrecision(12));
 const e=equity(state),marginUsed=p.trades.filter(t=>t.status==="OPEN").reduce((a,t)=>a+t.entry*t.quantity/s.leverage,0);const sized=sizeTrade(e,entry,stop,m.instrument,s,Math.max(0,e-marginUsed));if(!sized.quantity){reject(sized.reason);continue;}const aggregateRisk=p.trades.filter(t=>t.status==="OPEN").reduce((a,t)=>a+t.plannedRisk,0);if(aggregateRisk+sized.risk>e*.01){reject("Aggregate risk limit reached");continue;}
 const fee=entry*sized.quantity*Math.max(m.instrument.feeRate,s.feeBps/10000);p.balance-=fee;p.trades.push({id:crypto.randomUUID(),pair:m.pair,side:sig.action,quantity:sized.quantity,entry,stop,target,openedAt:now,pnl:0,fees:fee,funding:0,plannedRisk:sized.risk,status:"OPEN",lastBarTime:Math.floor(now/60000)*60000,lastFundingAt:now,strategy:sig.strategy});event(p,"ENTRY","Paper "+sig.action.toLowerCase()+" opened with simulated stop and target",m.pair);
 }}p.lastScan=now;p.equityCurve.push({time:now,equity:equity(state)});if(p.equityCurve.length>3000)p.equityCurve=p.equityCurve.filter((_,i)=>i%2===0);return state;}
export function liveGates(s:DeskState){const closed=s.portfolio.trades.filter(t=>t.status==="CLOSED"),days=(Date.now()-s.portfolio.startedAt)/86400000;return [{label:"Account connection verified",pass:s.connection.verified},{label:"Continuous worker with durable storage",pass:s.worker.continuous},{label:"30 days of forward observation",pass:days>=30},{label:"200 closed paper trades",pass:closed.length>=200},{label:"Positive paper expectancy",pass:closed.length>0&&closed.reduce((a,t)=>a+t.pnl,0)>0},{label:"Independent out-of-sample evidence",pass:false},{label:"Exchange protection and recovery verified",pass:false}];}
